import type { CollectionConfig, CollectionProduct } from "@/types/collection"

const DEFAULT_IMAGE =
  "https://res.cloudinary.com/dsieyc8m2/image/upload/v1776360259/g1b6li1pzvf73qu59dn5.webp"

// Honey Collection
export const honeyProducts: CollectionProduct[] = [
  {
    id: "h-1",
    name: "Sundarban Pure Honey (500g)",
    image: DEFAULT_IMAGE,
    price: 620,
    originalPrice: 780,
    discount: 21,
    flag: "Offered Items",
    category: "Sundarban",
    brand: "GhorerBazar",
  },
  {
    id: "h-2",
    name: "Black Seed (Kalojira) Honey (250g)",
    image: DEFAULT_IMAGE,
    price: 890,
    originalPrice: 1050,
    discount: 15,
    flag: "New Arrival",
    category: "Black Seed",
    brand: "Honeyraj",
  },
  {
    id: "h-3",
    name: "Lichu Flower Honey (500g)",
    image: DEFAULT_IMAGE,
    price: 540,
    originalPrice: 650,
    discount: 17,
    flag: "Offered Items",
    category: "Lichu Flower",
    brand: "GhorerBazar",
  },
  {
    id: "h-4",
    name: "Sidr Mountain Honey (250g)",
    image: DEFAULT_IMAGE,
    price: 1250,
    originalPrice: 1500,
    discount: 17,
    flag: "New Arrival",
    category: "Sidr",
    brand: "Honeyraj",
  },
  {
    id: "h-5",
    name: "Raw Honeycomb Block (400g)",
    image: DEFAULT_IMAGE,
    price: 980,
    originalPrice: 1200,
    discount: 18,
    flag: "Offered Items",
    category: "Honeycomb",
    brand: "GhorerBazar",
  },
  {
    id: "h-6",
    name: "Organic Wild Honey (1kg)",
    image: DEFAULT_IMAGE,
    price: 1450,
    originalPrice: 1700,
    discount: 15,
    flag: "New Arrival",
    category: "Organic",
    brand: "Honeyraj",
  },
  {
    id: "h-7",
    name: "Crystal Mustard Honey (500g)",
    image: DEFAULT_IMAGE,
    price: 480,
    originalPrice: 600,
    discount: 20,
    flag: "Offered Items",
    category: "Crystal Honey",
    brand: "GhorerBazar",
  },
  {
    id: "h-8",
    name: "Sundarban Khalisha Honey (1kg)",
    image: DEFAULT_IMAGE,
    price: 1180,
    originalPrice: 1400,
    discount: 16,
    flag: "New Arrival",
    category: "Sundarban",
    brand: "Honeyraj",
  },
  {
    id: "h-9",
    name: "Black Seed Honey (500g)",
    image: DEFAULT_IMAGE,
    price: 1650,
    originalPrice: 1900,
    discount: 13,
    flag: "Offered Items",
    category: "Black Seed",
    brand: "GhorerBazar",
  },
  {
    id: "h-10",
    name: "Lichu Flower Honey (1kg)",
    image: DEFAULT_IMAGE,
    price: 980,
    originalPrice: 1200,
    discount: 18,
    flag: "New Arrival",
    category: "Lichu Flower",
    brand: "Honeyraj",
  },
  {
    id: "h-11",
    name: "Sidr Honey (500g)",
    image: DEFAULT_IMAGE,
    price: 2200,
    originalPrice: 2600,
    discount: 15,
    flag: "Offered Items",
    category: "Sidr",
    brand: "GhorerBazar",
  },
  {
    id: "h-12",
    name: "Raw Organic Honey (500g)",
    image: DEFAULT_IMAGE,
    price: 720,
    originalPrice: 900,
    discount: 20,
    flag: "New Arrival",
    category: "Organic",
    brand: "Honeyraj",
  },
]

export const honeyConfig: CollectionConfig = {
  slug: "honey",
  title: "Honey",
  description:
    "Shop our full range of pure honey: Sundarban, Black Seed, Lichu Flower, Sidr, Honeycomb, Organic, and Crystal honey from trusted brands.",
  categories: [
    "Sundarban",
    "Black Seed",
    "Lichu Flower",
    "Sidr",
    "Honeycomb",
    "Organic",
    "Crystal Honey",
  ],
  brands: ["GhorerBazar", "Honeyraj"],
  flags: ["New Arrival", "Offered Items"],
  products: honeyProducts,
}

// Dates Collection
export const datesProducts: CollectionProduct[] = [
  {
    id: "d-1",
    name: "Premium Ajwa Dates (500g)",
    image: DEFAULT_IMAGE,
    price: 1850,
    originalPrice: 2200,
    discount: 16,
    flag: "New Arrival",
    category: "Ajwa",
    brand: "AlMadina",
  },
  {
    id: "d-2",
    name: "Medjool Dates Large (1kg)",
    image: DEFAULT_IMAGE,
    price: 2400,
    originalPrice: 2800,
    discount: 14,
    flag: "Offered Items",
    category: "Medjool",
    brand: "DateKing",
  },
  {
    id: "d-3",
    name: "Safawi Dates (500g)",
    image: DEFAULT_IMAGE,
    price: 680,
    originalPrice: 800,
    discount: 15,
    flag: "New Arrival",
    category: "Safawi",
    brand: "AlMadina",
  },
  {
    id: "d-4",
    name: "Khudri Dates (1kg)",
    image: DEFAULT_IMAGE,
    price: 520,
    originalPrice: 650,
    discount: 20,
    flag: "Offered Items",
    category: "Khudri",
    brand: "DateKing",
  },
  {
    id: "d-5",
    name: "Sukkari Dates (500g)",
    image: DEFAULT_IMAGE,
    price: 1100,
    originalPrice: 1300,
    discount: 15,
    flag: "New Arrival",
    category: "Sukkari",
    brand: "AlMadina",
  },
  {
    id: "d-6",
    name: "Mabroom Dates (500g)",
    image: DEFAULT_IMAGE,
    price: 950,
    originalPrice: 1150,
    discount: 17,
    flag: "Offered Items",
    category: "Mabroom",
    brand: "DateKing",
  },
  {
    id: "d-7",
    name: "Deglet Noor Dates (1kg)",
    image: DEFAULT_IMAGE,
    price: 780,
    originalPrice: 950,
    discount: 18,
    flag: "New Arrival",
    category: "Deglet Noor",
    brand: "AlMadina",
  },
  {
    id: "d-8",
    name: "Zahidi Dates (500g)",
    image: DEFAULT_IMAGE,
    price: 450,
    originalPrice: 550,
    discount: 18,
    flag: "Offered Items",
    category: "Zahidi",
    brand: "DateKing",
  },
]

export const datesConfig: CollectionConfig = {
  slug: "dates",
  title: "Dates",
  description:
    "Discover our premium selection of dates: Ajwa, Medjool, Safawi, Khudri, Sukkari, and more from trusted brands.",
  categories: [
    "Ajwa",
    "Medjool",
    "Safawi",
    "Khudri",
    "Sukkari",
    "Mabroom",
    "Deglet Noor",
    "Zahidi",
  ],
  brands: ["AlMadina", "DateKing"],
  flags: ["New Arrival", "Offered Items"],
  products: datesProducts,
}

// Organic Collection
export const organicProducts: CollectionProduct[] = [
  {
    id: "o-1",
    name: "Organic Brown Rice (1kg)",
    image: DEFAULT_IMAGE,
    price: 180,
    originalPrice: 220,
    discount: 18,
    flag: "New Arrival",
    category: "Rice",
    brand: "GreenLife",
  },
  {
    id: "o-2",
    name: "Organic Quinoa (500g)",
    image: DEFAULT_IMAGE,
    price: 650,
    originalPrice: 780,
    discount: 17,
    flag: "Offered Items",
    category: "Grains",
    brand: "NatureFresh",
  },
  {
    id: "o-3",
    name: "Organic Chia Seeds (250g)",
    image: DEFAULT_IMAGE,
    price: 450,
    originalPrice: 550,
    discount: 18,
    flag: "New Arrival",
    category: "Seeds",
    brand: "GreenLife",
  },
  {
    id: "o-4",
    name: "Organic Flax Seeds (500g)",
    image: DEFAULT_IMAGE,
    price: 320,
    originalPrice: 400,
    discount: 20,
    flag: "Offered Items",
    category: "Seeds",
    brand: "NatureFresh",
  },
  {
    id: "o-5",
    name: "Organic Coconut Oil (500ml)",
    image: DEFAULT_IMAGE,
    price: 580,
    originalPrice: 700,
    discount: 17,
    flag: "New Arrival",
    category: "Oils",
    brand: "GreenLife",
  },
  {
    id: "o-6",
    name: "Organic Olive Oil (500ml)",
    image: DEFAULT_IMAGE,
    price: 1200,
    originalPrice: 1450,
    discount: 17,
    flag: "Offered Items",
    category: "Oils",
    brand: "NatureFresh",
  },
]

export const organicConfig: CollectionConfig = {
  slug: "organic",
  title: "Organic",
  description:
    "Shop certified organic products: rice, grains, seeds, oils, and more from trusted organic brands.",
  categories: ["Rice", "Grains", "Seeds", "Oils"],
  brands: ["GreenLife", "NatureFresh"],
  flags: ["New Arrival", "Offered Items"],
  products: organicProducts,
}

// Spices Collection
export const spicesProducts: CollectionProduct[] = [
  {
    id: "s-1",
    name: "Premium Turmeric Powder (200g)",
    image: DEFAULT_IMAGE,
    price: 120,
    originalPrice: 150,
    discount: 20,
    flag: "New Arrival",
    category: "Ground Spices",
    brand: "SpiceMaster",
  },
  {
    id: "s-2",
    name: "Whole Cumin Seeds (250g)",
    image: DEFAULT_IMAGE,
    price: 180,
    originalPrice: 220,
    discount: 18,
    flag: "Offered Items",
    category: "Whole Spices",
    brand: "AromaSpice",
  },
  {
    id: "s-3",
    name: "Red Chili Powder (200g)",
    image: DEFAULT_IMAGE,
    price: 95,
    originalPrice: 120,
    discount: 21,
    flag: "New Arrival",
    category: "Ground Spices",
    brand: "SpiceMaster",
  },
  {
    id: "s-4",
    name: "Cinnamon Sticks (100g)",
    image: DEFAULT_IMAGE,
    price: 220,
    originalPrice: 280,
    discount: 21,
    flag: "Offered Items",
    category: "Whole Spices",
    brand: "AromaSpice",
  },
  {
    id: "s-5",
    name: "Garam Masala (150g)",
    image: DEFAULT_IMAGE,
    price: 165,
    originalPrice: 200,
    discount: 18,
    flag: "New Arrival",
    category: "Blends",
    brand: "SpiceMaster",
  },
  {
    id: "s-6",
    name: "Black Pepper Whole (200g)",
    image: DEFAULT_IMAGE,
    price: 350,
    originalPrice: 420,
    discount: 17,
    flag: "Offered Items",
    category: "Whole Spices",
    brand: "AromaSpice",
  },
]

export const spicesConfig: CollectionConfig = {
  slug: "spices",
  title: "Spices",
  description:
    "Discover premium spices: ground spices, whole spices, and expertly crafted blends from trusted brands.",
  categories: ["Ground Spices", "Whole Spices", "Blends"],
  brands: ["SpiceMaster", "AromaSpice"],
  flags: ["New Arrival", "Offered Items"],
  products: spicesProducts,
}

// Nuts & Seeds Collection
export const nutsProducts: CollectionProduct[] = [
  {
    id: "n-1",
    name: "Premium Almonds (500g)",
    image: DEFAULT_IMAGE,
    price: 850,
    originalPrice: 1000,
    discount: 15,
    flag: "New Arrival",
    category: "Almonds",
    brand: "NutHouse",
  },
  {
    id: "n-2",
    name: "Cashew Nuts (500g)",
    image: DEFAULT_IMAGE,
    price: 780,
    originalPrice: 950,
    discount: 18,
    flag: "Offered Items",
    category: "Cashews",
    brand: "CrunchyNuts",
  },
  {
    id: "n-3",
    name: "Walnuts Premium (250g)",
    image: DEFAULT_IMAGE,
    price: 550,
    originalPrice: 680,
    discount: 19,
    flag: "New Arrival",
    category: "Walnuts",
    brand: "NutHouse",
  },
  {
    id: "n-4",
    name: "Pistachios Roasted (250g)",
    image: DEFAULT_IMAGE,
    price: 620,
    originalPrice: 750,
    discount: 17,
    flag: "Offered Items",
    category: "Pistachios",
    brand: "CrunchyNuts",
  },
  {
    id: "n-5",
    name: "Mixed Dry Fruits (500g)",
    image: DEFAULT_IMAGE,
    price: 950,
    originalPrice: 1150,
    discount: 17,
    flag: "New Arrival",
    category: "Mixed",
    brand: "NutHouse",
  },
  {
    id: "n-6",
    name: "Pumpkin Seeds (250g)",
    image: DEFAULT_IMAGE,
    price: 320,
    originalPrice: 400,
    discount: 20,
    flag: "Offered Items",
    category: "Seeds",
    brand: "CrunchyNuts",
  },
]

export const nutsConfig: CollectionConfig = {
  slug: "nuts-seeds",
  title: "Nuts & Seeds",
  description:
    "Premium nuts and seeds: almonds, cashews, walnuts, pistachios, and healthy seeds from trusted brands.",
  categories: ["Almonds", "Cashews", "Walnuts", "Pistachios", "Mixed", "Seeds"],
  brands: ["NutHouse", "CrunchyNuts"],
  flags: ["New Arrival", "Offered Items"],
  products: nutsProducts,
}

// Beverage Collection
export const beverageProducts: CollectionProduct[] = [
  {
    id: "b-1",
    name: "Premium Green Tea (100g)",
    image: DEFAULT_IMAGE,
    price: 280,
    originalPrice: 350,
    discount: 20,
    flag: "New Arrival",
    category: "Tea",
    brand: "TeaLeaf",
  },
  {
    id: "b-2",
    name: "Organic Coffee Beans (500g)",
    image: DEFAULT_IMAGE,
    price: 650,
    originalPrice: 800,
    discount: 19,
    flag: "Offered Items",
    category: "Coffee",
    brand: "BeanBrew",
  },
  {
    id: "b-3",
    name: "Chamomile Tea (50g)",
    image: DEFAULT_IMAGE,
    price: 220,
    originalPrice: 280,
    discount: 21,
    flag: "New Arrival",
    category: "Tea",
    brand: "TeaLeaf",
  },
  {
    id: "b-4",
    name: "Instant Coffee Powder (200g)",
    image: DEFAULT_IMAGE,
    price: 380,
    originalPrice: 450,
    discount: 16,
    flag: "Offered Items",
    category: "Coffee",
    brand: "BeanBrew",
  },
  {
    id: "b-5",
    name: "Herbal Tea Mix (100g)",
    image: DEFAULT_IMAGE,
    price: 320,
    originalPrice: 400,
    discount: 20,
    flag: "New Arrival",
    category: "Tea",
    brand: "TeaLeaf",
  },
  {
    id: "b-6",
    name: "Cold Brew Coffee (500ml)",
    image: DEFAULT_IMAGE,
    price: 180,
    originalPrice: 220,
    discount: 18,
    flag: "Offered Items",
    category: "Coffee",
    brand: "BeanBrew",
  },
]

export const beverageConfig: CollectionConfig = {
  slug: "beverage",
  title: "Beverage",
  description:
    "Premium beverages: green tea, herbal tea, organic coffee, cold brew, and more from trusted brands.",
  categories: ["Tea", "Coffee"],
  brands: ["TeaLeaf", "BeanBrew"],
  flags: ["New Arrival", "Offered Items"],
  products: beverageProducts,
}

// Rice Collection
export const riceProducts: CollectionProduct[] = [
  {
    id: "r-1",
    name: "Basmati Rice Premium (5kg)",
    image: DEFAULT_IMAGE,
    price: 850,
    originalPrice: 1000,
    discount: 15,
    flag: "New Arrival",
    category: "Basmati",
    brand: "RiceKing",
  },
  {
    id: "r-2",
    name: "Chinigura Rice (2kg)",
    image: DEFAULT_IMAGE,
    price: 380,
    originalPrice: 450,
    discount: 16,
    flag: "Offered Items",
    category: "Aromatic",
    brand: "GoldenGrain",
  },
  {
    id: "r-3",
    name: "Miniket Rice (5kg)",
    image: DEFAULT_IMAGE,
    price: 420,
    originalPrice: 500,
    discount: 16,
    flag: "New Arrival",
    category: "Miniket",
    brand: "RiceKing",
  },
  {
    id: "r-4",
    name: "Nazirshail Rice (5kg)",
    image: DEFAULT_IMAGE,
    price: 450,
    originalPrice: 550,
    discount: 18,
    flag: "Offered Items",
    category: "Aromatic",
    brand: "GoldenGrain",
  },
  {
    id: "r-5",
    name: "Brown Rice (2kg)",
    image: DEFAULT_IMAGE,
    price: 280,
    originalPrice: 350,
    discount: 20,
    flag: "New Arrival",
    category: "Brown Rice",
    brand: "RiceKing",
  },
  {
    id: "r-6",
    name: "Sticky Rice (1kg)",
    image: DEFAULT_IMAGE,
    price: 180,
    originalPrice: 220,
    discount: 18,
    flag: "Offered Items",
    category: "Sticky",
    brand: "GoldenGrain",
  },
]

export const riceConfig: CollectionConfig = {
  slug: "rice",
  title: "Rice",
  description:
    "Premium rice varieties: Basmati, Chinigura, Miniket, Nazirshail, Brown Rice, and more from trusted brands.",
  categories: ["Basmati", "Aromatic", "Miniket", "Brown Rice", "Sticky"],
  brands: ["RiceKing", "GoldenGrain"],
  flags: ["New Arrival", "Offered Items"],
  products: riceProducts,
}

// Flours & Lentils Collection
export const floursProducts: CollectionProduct[] = [
  {
    id: "f-1",
    name: "Whole Wheat Flour (2kg)",
    image: DEFAULT_IMAGE,
    price: 120,
    originalPrice: 150,
    discount: 20,
    flag: "New Arrival",
    category: "Flour",
    brand: "MillFresh",
  },
  {
    id: "f-2",
    name: "Red Lentils (1kg)",
    image: DEFAULT_IMAGE,
    price: 180,
    originalPrice: 220,
    discount: 18,
    flag: "Offered Items",
    category: "Lentils",
    brand: "PulsePlus",
  },
  {
    id: "f-3",
    name: "Chickpea Flour (1kg)",
    image: DEFAULT_IMAGE,
    price: 140,
    originalPrice: 170,
    discount: 18,
    flag: "New Arrival",
    category: "Flour",
    brand: "MillFresh",
  },
  {
    id: "f-4",
    name: "Yellow Lentils (1kg)",
    image: DEFAULT_IMAGE,
    price: 160,
    originalPrice: 200,
    discount: 20,
    flag: "Offered Items",
    category: "Lentils",
    brand: "PulsePlus",
  },
  {
    id: "f-5",
    name: "Rice Flour (1kg)",
    image: DEFAULT_IMAGE,
    price: 95,
    originalPrice: 120,
    discount: 21,
    flag: "New Arrival",
    category: "Flour",
    brand: "MillFresh",
  },
  {
    id: "f-6",
    name: "Green Lentils (1kg)",
    image: DEFAULT_IMAGE,
    price: 220,
    originalPrice: 280,
    discount: 21,
    flag: "Offered Items",
    category: "Lentils",
    brand: "PulsePlus",
  },
]

export const floursConfig: CollectionConfig = {
  slug: "flours-lentils",
  title: "Flours & Lentils",
  description:
    "Quality flours and lentils: whole wheat, chickpea flour, red lentils, yellow lentils, and more.",
  categories: ["Flour", "Lentils"],
  brands: ["MillFresh", "PulsePlus"],
  flags: ["New Arrival", "Offered Items"],
  products: floursProducts,
}

// Collection map for easy lookup
export const collectionConfigs: Record<string, CollectionConfig> = {
  honey: honeyConfig,
  dates: datesConfig,
  organic: organicConfig,
  spices: spicesConfig,
  "nuts-seeds": nutsConfig,
  beverage: beverageConfig,
  rice: riceConfig,
  "flours-lentils": floursConfig,
}

export function getCollectionConfig(slug: string): CollectionConfig | null {
  return collectionConfigs[slug] || null
}
